import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect } from 'react'
import { useTranslation } from 'next-i18next'
import classNames from 'classnames/bind'
import styles from './style.module.scss'
import { GetStaticProps } from 'next'
import ArrowIcon from '../assets/icons/arrow.svg'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { fetchPokemon } from '@/api/fetchPokemon'

const cx = classNames.bind(styles)

export default function Home() {
  const router = useRouter()
  const { t } = useTranslation('common')
  const changeLanguage = (locale: string) => {
    router.push(router.pathname, router.asPath, { locale })
  }
  useEffect(() => {
    const fetchPokemonBerry = async () => {
      const res = await fetchPokemon({
        name: 'oran',
      })
      return res
    }
    const res = fetchPokemonBerry()
    console.log('pokemon berry', res)
  }, [])
  return (
    <>
      <Head>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={cx('container')}>
        <div className={cx('title')}>{t('title')}</div>
        <div className={cx('description')}>{t('description')}</div>
        <div className={cx('wrapper')}>
          <button className={cx('button')} onClick={() => changeLanguage('zh-TW')}>
            中文
          </button>
          <button className={cx('button')} onClick={() => changeLanguage('en')}>
            English
          </button>
        </div>
        <div className={cx('icon-sample')}>
          <span className={cx('description')}>icon-sample</span>
          <ArrowIcon width={20} height={20} color='green' />
        </div>
      </div>
    </>
  )
}
export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale ?? 'zh', ['common'])),
    },
  }
}
